name: Checks

on:
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
